"""Provider/pipeline abstractions so concrete AI providers can be swapped
without touching calling code.

TODO: define abstract base classes, e.g.:
    class OCRProvider(ABC): ...
    class LLMProvider(ABC): ...
    class EmbeddingProvider(ABC): ...
    class DocumentProcessor(ABC): ...
    class RetrievalProvider(ABC): ...
    class VerificationProvider(ABC): ...
"""
